# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

definitions:
  workspace: &workspace
    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/ysugimoto/ginger
    docker:
      # specify the version
      - image: circleci/golang:1.9.3

  job_presets: &job_presets
    build:
      <<: *workspace
      steps:
        - checkout
        - run:
           command: |
             curl -L -o $GOPATH/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
             chmod +x $GOPATH/bin/dep
        - run:
           command: |
             cd /go/src/github.com/ysugimoto/ginger
             dep ensure
             cd vendor/github.com/mattn/go-bindata && go install .
             cd /go/src/github.com/ysugimoto/ginger
             make production
        - persist_to_workspace:
           root: /go/src/github.com/ysugimoto/ginger
           paths:
             - ./*
    publish:
      <<: *workspace
      steps:
        - attach_workspace:
            at: /go/src/github.com/ysugimoto/ginger
        - setup_remote_docker
        - run:
           command: |
             sudo apt-get install python-setuptools
             sudo apt-get install python-pip
             sudo pip install awscli
             export PATH=$PATH:/usr/local/bin
             cd /go/src/github.com/ysugimoto/ginger
             make publish

jobs:
  <<: *job_presets

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
